// <auto-generated />
namespace WebDrive.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addColumnSharefileNamefileType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addColumnSharefileNamefileType));
        
        string IMigrationMetadata.Id
        {
            get { return "201505270333252_addColumn-Share.fileName.fileType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
