// <auto-generated />
namespace WebDrive.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addTableRecoder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTableRecoder));
        
        string IMigrationMetadata.Id
        {
            get { return "201505270653323_addTable-Recoder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
