// <auto-generated />
namespace WebDrive.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addMD5RealFile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addMD5RealFile));
        
        string IMigrationMetadata.Id
        {
            get { return "201505151411332_add-MD5-RealFile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
