// <auto-generated />
namespace WebDrive.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addCondition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCondition));
        
        string IMigrationMetadata.Id
        {
            get { return "201505090747344_addCondition"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
