// <auto-generated />
namespace WebDrive.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class validationup1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(validationup1));
        
        string IMigrationMetadata.Id
        {
            get { return "201505130642475_validation-up1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
