// <auto-generated />
namespace WebDrive.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addUserFile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addUserFile));
        
        string IMigrationMetadata.Id
        {
            get { return "201505230324058_add-UserFile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
