// <auto-generated />
namespace WebDrive.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class modifyColumnNameShare : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifyColumnNameShare));
        
        string IMigrationMetadata.Id
        {
            get { return "201505270341293_modifyColumnName-Share"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
