// <auto-generated />
namespace WebDrive.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addTableRealFile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTableRealFile));
        
        string IMigrationMetadata.Id
        {
            get { return "201505140608440_addTable-RealFile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
